### ISSUE TITLE
Unexpected behavior of `shouldThrow`

### ISSUE THREAD

**Issue by fsantanna** [gflima/ceu.hs#3]
https://github.com/gflima/ceu.hs/blob/ce9e223a55ecfb0df2667851c4d2a3d3fd088719/CeuSpec.hs#L35

This test case fails even though running this code in a separate file alone generates the indicated error in the test case.

The same happens for 10 other cases using `shouldThrow`.

Any ideas?

**Comment by fsantanna** [comment]
In the `env` branch.

**Comment by gflima** [comment]
The problem was caused by `evaluate` which was not completely evaluating the given expression.  Using `(evaluate . force)` in the cases where this was happening fixed the problem.  For this solution to work, however, I had to make `Stmt` a subclass of `NFData`.
